services:
  - type: web
    name: heat-wave-alert-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: android-e489f-firebase-adminsdk-9zb83-01114e83ab.json
